# Generated by Django 3.2.5 on 2021-08-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESM_Server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esm',
            name='boot_time',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='cpu_core',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='cpu_load',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='login_users',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='ram_available',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='ram_free',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='ram_percent',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='ram_total',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='ram_used',
        ),
        migrations.AddField(
            model_name='esm',
            name='client_password',
            field=models.CharField(default='', max_length=1024, verbose_name='密码'),
        ),
    ]
